apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lastic-operator
spec:
  releaseName: elastic-operator
  chart:
    spec:
      chart: elastic/eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  interval: 5m
  install:
    remediation:
      retries: 3
