---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: application-component-podinfo
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/apps/podinfo
  prune: true
  wait: true


# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: apps
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   # dependsOn:
#   #   - name: infra-configs
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./software/stamp-instance
#   prune: true
#   wait: true
#   timeout: 5m0s
