apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certmgr
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    installCRDs: true
  interval: 5m0s
  releaseName: certmgr
  targetNamespace: cert-manager
