---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: controllers
  namespace: flux-system
spec:
  interval: 5m
  path: "./controllers"
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxsetup
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: configs
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers
  interval: 5m
  path: "./configs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxsetup

