---
apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: autoscaling
spec:
  elasticsearchRef:
    name: elasticsearch-ha
  policies:
    - name: master
      roles: ["master"]
      resources:
        nodeCount:
          min: 3
          max: 5
---
# This sets up an Elasticsearch cluster with 3 nodes.
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-ha
  namespace: elastic-search
spec:
  version: 8.5.0
  nodeSets:
  - name: master
    count: 3
    config:
      node:
        roles: [ "master" ]
        store.allow_mmap: false
    podTemplate:
      spec:
        tolerations:
          - effect: NoSchedule
            key: app
            value: 'elasticsearch'
        containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 4Gi
                cpu: 2
        env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"


  - name: coordinating
    count: 3
    config:
      node:
        roles: [ ]
        store.allow_mmap: false
    podTemplate:
      spec:
        tolerations:
          - effect: NoSchedule
            key: app
            value: 'elasticsearch'


  - name: data
    count: 3
    config:
      node:
        roles: [ "data" ]
        store.allow_mmap: false
    podTemplate:
      spec:
        tolerations:
          - effect: NoSchedule
            key: app
            value: 'elasticsearch'
